### ISSUE TITLE
Перечень пакетов. Пакет ФБ

### ISSUE THREAD

**Issue by DKAndronchyk** [bcrypto/skzi#12]
Неясна цель появления некоторых требований пакета ФБ, а именно
а) **Требование ФБ.2 Аппаратные КСК должны быть изготовлены промышленным способом.** - _нет определения "промышленного способа". Это только на предприятиях Министерства промышленности?_ 
б) **Требование ФБ.3  Аппаратные КСК должны иметь покрытие, обеспечивающее
защиту от воздействия окружающей среды.
Примечание 1 — Например, может использоваться лакокрасочное покрытие в соответствии
с ГОСТ 9.306.** _- любое покрытие обеспечивает какую-то защиту от какой-то окружающей среды. Приведённый в примечании ТНПА вообще устанавливает требования не к покрытиям, а к их обозначениям!_
_Требования ФБ.2 и ФБ.3, возможно, вводились с целью подтверждения отказоустойчивости аппаратных СКЗИ. Но тогда почему нет ровным счётом ничего про отказоустойчивость программных СКЗИ или программных модулей аппаратных СКЗИ? **Предложение** - исключить данные требования или дополнить ТНПА требованиями отказоустойчивости всего СКЗИ, а не корпуса._
в) **Требование ФБ.4 СКЗИ должен быть окружен твердым непрозрачным корпусом и (или) покрытием. Визуальный осмотр СКЗИ не должен давать информацию о внутреннем устройстве и внутренних компонентах СКЗИ.
Примечание 2 — Требование означает, что корпус не содержит незащищённые отверстия или элементы, прозрачные в видимой части спектра.** _- при попытке соответствовать этому требованию придётся полностью отказаться от аппаратных платформ с активным воздушным охлаждением и оставить только пассивное охлаждение и жидкостное. Следует отметить, что требование распространяется на СКЗИ уровней 3 и 4, где предполагается высококвалифицированный и хорошо оснащённый злоумышленник, который почему-то вдруг ограничен "видимой частью спектра"? Проект ТНПА предполагается распространять на СКЗИ работающие с несекретной информацией по открытым алгоритмам и протоколам, спецификации таких СКЗИ должны быть открытыми для всех потенциальных покупателей. Что именно предлагается скрывать в "закрытом от всех глаз" корпусе? **Предложение:** исключить требование._

**Comment by agievich** [comment]
Вопрос разбит на 3 части: #13, #14, #15. Обсуждение переносится в эти части.
