### ISSUE TITLE
Пакет ФБ: промышленный способ

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#13]
>**Требование ФБ.2.** Аппаратные КСК должны быть изготовлены промышленным способом. 

Нет определения "промышленного способа". Это только на предприятиях Министерства промышленности?

**Comment by rashchenia** [comment]
Под промышленным способом понимается изготовление аппаратных КСК в соответствии 
с действующей технической документацией на них (например, функциональной 
спецификацией или техническими условиями). Т.е. аппаратные КСК должны быть 
изготовлены таким образом, чтобы соответствовать техническим характеристикам, 
заявленным в технической документации на них. 

В FIPS 140-3 применяется термин "production-grade":
> product, component or software that has been tested to meet operational 
specifications. 

Требование о применении соответствующих компонент установлено в FIPS 140-3 в разделе 
Физическая безопасность с первого уровня: 
> the cryptographic module shall [07.15] consist of production-grade components 
that include standard passivation techniques (e.g. a conformal coating or a 
sealing coat applied over the module’s circuitry to protect against 
environmental or other physical damage)". Т.е. в FIPS 140-3 требуется, чтобы 
все компоненты криптографического модуля соответствовали требованиям 
функциональных спецификаций на них.

Цель требования -- исключить применение в СКЗИ в качестве аппаратных КСК 
компонент, для которых их изготовителем либо не определены функциональные 
характеристики, либо не подтверждено их соответствие заявленным функциональным 
характеристикам. Т.к. если нет подтверждения базового уровня надежности 
компонент, то сложно гарантировать безопасность, обеспечиваемую их применением. 

**Пример**. Пусть в СКЗИ для контроля какого-либо критического параметра
необходимо применить специализированную микросхему или датчик. Если погрешность
измерений данной микросхемы или надежность датчика не заявлены производителем
или не соответствуют предъявляемым требованиям, то применение такой микросхемы
или датчика потенциально небезопасно.

Для уточнения требования может быть введено примечание: 
> Под компонентом, изготовленным промышленным способом, понимается компонент, 
изготовленный в соответствии с требованиями технической документации на него 
(например, в соответствии с функциональной спецификацией или техническими 
условиями).

**Comment by agievich** [comment]
Вопрос перенесен в #18.
