### ISSUE TITLE
Пакет ФБ: покрытие

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#14]
>**Требование ФБ.3**. Аппаратные КСК должны иметь покрытие, обеспечивающее
защиту от воздействия окружающей среды.

**Комментарий 1**. Например, может использоваться лакокрасочное покрытие в соответствии
с ГОСТ 9.306. - любое покрытие обеспечивает какую-то защиту от какой-то окружающей среды. Приведённый в примечании ТНПА вообще устанавливает требования не к покрытиям, а к их обозначениям!

**Комментарий 2**. Требования ФБ.2 и ФБ.3, возможно, вводились с целью подтверждения отказоустойчивости аппаратных СКЗИ. Но тогда почему нет ровным счётом ничего про отказоустойчивость программных СКЗИ или программных модулей аппаратных СКЗИ? 

**Предложение**. Исключить данные требования или дополнить ТНПА требованиями отказоустойчивости всего СКЗИ, а не корпуса.

**Comment by rashchenia** [comment]
Требование о наличии у аппаратных КСК покрытия, обеспечивающего защиту от 
воздействия окружающей среды, введено с целью обеспечения для них базового 
уровня надежности и отказоустойчивости с учетом потенциальных агрессивных 
воздействий окружающей среды.

Введенное требование перекликается с требованиями FIPS 140-3, установленными 
для компонентов криптографического модуля в разделе Физическая безопасность с 
первого уровня:
> the cryptographic module shall [07.15] consist of production-grade components 
that include standard passivation techniques (e.g. a conformal coating or a 
sealing coat applied over the module’s circuitry to protect against 
environmental or other physical damage). 

Т.е. в FIPS 140-3 требуется, чтобы все компоненты криптографического модуля 
соответствовали указанным требованиям. Но это требование обязательно только для 
аппаратных (программно-аппаратных) компонент. Соответствующее указание о том, 
что требования раздела 7.7 Физическая безопасность опциональны для программных 
криптографических модулей приведено в подразделе 7.2.2: 
> For software modules executing in a modifiable environment, the physical 
security requirements found in 7.7 are optional. 
 
И это логично, потому что, например, нельзя требовать наличия защитного 
покрытия у программного СКЗИ.

Не совсем верно, что требования по надежности и отказоустойчивости не 
предъявлены в проекте стандарта к программным средствам. Соответствующие 
требования предъявлены, как минимум, в части обеспечения контроля правильности 
функционирования КСК (см. пакет Самотестирование (СТ)), а также подтверждения 
корректности реализации программ СКЗИ (см. пакет Анализ программ (АП)). 
Соответственно, добавление требований по отказоустойчивости программных СКЗИ 
излишне. 

Неверно, что требование предъявлено к корпусу. Оно предъявлено к аппаратным 
КСК. Требование представляется логичным, т.к. обеспечивает базовый уровень 
защиты аппаратных КСК.

**Пример**. Пусть в СКЗИ имеется контактная площадка для замыкания цепи датчика 
контроля вскрытия. Если площадка не будет защищена от воздействия окружающей 
среды, то со временем рано или поздно она, например, окислится, пропадет 
контакт, произойдет ложное срабатывание или отказ датчика контроля вскрытия, 
которые нельзя будет устранить силами потребителя СКЗИ. 

Более того, при современном производстве электронных систем в любом случае
применяется какое-либо защитное конструктивное покрытие. Например, иммерсионное 
золочение или паяльная маска контактных площадок и концевых ламелей, слой 
диэлектрической защиты (лак, эмаль, пленочные резисты и т.п.) печатных плат.

Другой вопрос, что наличие такого требования приводит к потенциальным проблемам 
при разработке методик проверки соответствия (сертификации). Т.к. потребуется 
определить методы испытаний. Поэтому если в методиках можно будет ограничиться 
экспертной оценкой наличия защитного покрытия, то требование надо оставлять. 
Иначе может надо и исключить. Либо объединить с требованием по промышленному 
способу изготовления, по аналогии с FIPS 140-3: 
> Аппаратные КСК должны быть изготовлены промышленным способом и иметь 
стандартное покрытие, обеспечивающее защиту от воздействия окружающей среды. 

В случае объединения в одно требование защитное покрытие увязывается с 
промышленным изготовлением и может проверяться в связке с проверкой на 
соответствие технической документации аппаратного КСК. 

Касательно примечания. В нем требования не установлены. Приведен пример со 
ссылкой на лакокрасочное покрытие по ГОСТ 9.306. Имелось в виду как раз 
обозначение, а не требования к лакокрасочному покрытию. Для исключения 
неоднозначности предлагается исключить примечание. Т.к. устанавливать 
требования по соответствию какому-либо стандарту в общем случае 
нецелесообразно.

**Comment by agievich** [comment]
**Предлагается** сохранить примечание, исключив в нем ссылку на ГОСТ 9.306 и одновременно добавив больше примеров защитного покрытия:

> Примечание. Может использоваться лакокрасочное покрытие, <пример 2>, <пример 3>.

**Comment by DKAndronchyk** [comment]
> **Предлагается** сохранить примечание, исключив в нем ссылку на ГОСТ 9.306 и одновременно добавив больше примеров защитного покрытия:
> 
> > Примечание. Может использоваться лакокрасочное покрытие, <пример 2>, <пример 3>.

Пример: если корпус цельный из алюминиевого или титанового сплавов, то формально он не удовлетворяет требованию в такой формулировке, но фактически очень даже защищён от внешних воздействий. Это же касается и пластиковых корпусов без окраски.
Предлагаю следующую формулировку:
>>Аппаратные КСК должны иметь корпус, обеспечивающий защиту от воздействия окружающей среды.

и без примечаний.

**Comment by agievich** [comment]
> Аппаратные КСК должны иметь корпус, обеспечивающий защиту от воздействия окружающей среды.

Нет, так нельзя. Не всякое аппаратное КСК имеет корпус. 

> и без примечаний.

Примечание не содержит требований. Только разъяснения. Не вижу проблемы с примерами покрытий.

**Comment by DKAndronchyk** [comment]
> Нет, так нельзя. Не всякое аппаратное КСК имеет корпус.

Аппаратное КСК не имеет корпуса, но имеет защитное покрытие, например лакокрасочное? Можно пример?

**Comment by agievich** [comment]
> Можно пример?

Плата, залитая компаундом.

Обсуждение темы переносится в #19.
