### ISSUE TITLE
Пакет ФБ: корпус

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#15]
>**Требование ФБ.4.** СКЗИ должен быть окружен твердым непрозрачным корпусом и (или) покрытием. Визуальный осмотр СКЗИ не должен давать информацию о внутреннем устройстве и внутренних компонентах СКЗИ.

**Комментарий.** Требование означает, что корпус не содержит незащищённые отверстия или элементы, прозрачные в видимой части спектра. - при попытке соответствовать этому требованию придётся полностью отказаться от аппаратных платформ с активным воздушным охлаждением и оставить только пассивное охлаждение и жидкостное. Следует отметить, что требование распространяется на СКЗИ уровней 3 и 4, где предполагается высококвалифицированный и хорошо оснащённый злоумышленник, который почему-то вдруг ограничен "видимой частью спектра"? Проект ТНПА предполагается распространять на СКЗИ работающие с несекретной информацией по открытым алгоритмам и протоколам, спецификации таких СКЗИ должны быть открытыми для всех потенциальных покупателей. Что именно предлагается скрывать в "закрытом от всех глаз" корпусе? 

**Предложение**. Исключить требование.

**Comment by rashchenia** [comment]
В соответствии с моделью нарушителя, приведенной в п. 4.3 проекта стандарта, противник базовой квалификации проводит эксперименты с образцами СКЗИ, изучает руководства, среднего уровня проводит эксперименты с образцами СКЗИ, изучает руководства, проводит анализ программного обеспечения СКЗИ и КСК. Противник высокого уровня дополнительно проводит исследование аппаратных КСК и аппаратных компонентов СКЗИ, изучает поведение компонентов при внешних воздействиях, ведет поиск уязвимостей, снова использует сведения об известных уязвимостях. При этом противник средней квалификации соотнесен со 2 и 3 уровнями СКЗИ, противник высокой квалификации -- с уровнем 4 СКЗИ.

Требование ФБ.4 действует с третьего уровня и не противоречит приведенной модели нарушителя. Если исключить данное требование, то для СКЗИ 3 уровня противник даже самого низкого уровня без наличия каких-либо сведений о СКЗИ будет иметь потенциальную возможность по результатам визуального осмотра внутреннего устройства СКЗИ, например, определить места размещения и подключения средств технического контроля доступа и, возможно, использовать полученные сведения для их обхода. Нарушитель высокого уровня при наличии незащищенных отверстий может попытаться их использовать для внесения изменений в конструкцию СКЗИ, приводящих к возникновению побочных каналов утечки информации. Наличие элементов, прозрачных в видимой части спектра (например, как сейчас модно, большое прозрачное окно в корпусе ПЭВМ), также потенциально небезопасно, т.к. увеличивает возможности утечки информации посредством побочных излучений. Ограничение визуального доступа позволяет минимизировать указанные угрозы относительно простым конструктивным способом, при том, что при оценке соответствия СКЗИ методика проверки будет простой. С учетом вышеуказанного исключать требование нецелесообразно.

В FIPS 140-3 аналогичное требование введено со 2 уровня:
> the tamper-evident material, coating or enclosure shall [07.19] either be opaque or translucent within the visible spectrum (i.e. light of wavelength range of 400nm to 750nm) to prevent the gathering of information about the internal operations of the critical areas of the module; and
if the cryptographic module contains ventilation holes or slits, then the module shall [07.20] be constructed in a manner to prevent the gathering of information of the module’s internal construction or components by direct visual observation using artificial light sources in the visual spectrum of the module’s internal construction or components.

Действительно, вентиляционные отверстия должны быть. Если корпус СКЗИ разрабатывается вместе с разработкой СКЗИ, то возможно реализовать вентиляционные отверстия, через которые исключен визуальный осмотр внутреннего устройства СКЗИ. Если используется покупная ПЭВМ, в которую добавляется ПО, то и в этом случае представляется возможным обеспечить выполнение требования. Кроме того, в этом случае СКЗИ можно классифицировать как программное средство, например, 2 уровня, что позволит не соответствовать требованиям физической безопасности.

**Comment by DKAndronchyk** [comment]
> В FIPS 140-3 аналогичное требование введено со 2 уровня:

Вездесущие ссылки на FIPS 140-3 были бы уместны при полном его переводе, а не творческой переработке. Все стандарты и рекомендации правильнее использовать целиком, а не выдёргивать приглянувшиеся кусочки.

>  Если используется покупная ПЭВМ, в которую добавляется ПО, то и в этом случае представляется возможным обеспечить выполнение  требования.

Без приведения примера утверждение голословно. Я обращал внимание, что введение стандарта, которому затруднительно или невозможно соответствовать - бессмысленно. Ещё раз повторюсь: Проект ТНПА предполагается распространять на СКЗИ работающие с несекретной информацией по открытым алгоритмам и протоколам, спецификации таких СКЗИ  **_должны быть открытыми для всех потенциальных покупателей_**.
Соответственно, знание внутреннего устройства СКЗИ будет у противника любого уровня

**Comment by agievich** [comment]
> Все стандарты и рекомендации правильнее использовать целиком, а не выдёргивать приглянувшиеся кусочки.

Странный стиль. Неуместный здесь. Да, мы читали FIPS 140-1, 2, 3. И перечитывали. И сверяемся с FIPS 140. Странно этого не делать. Если последовать совету и принять FIPS 140-3, то защита от визуального осмотра будет требоваться уже на 2-м уровне. Для обычных (коммерческая информация) СКЗИ. В этом суть выдвинутого предложения?

Да, принятая в Проекте модель противника максимально благоприятна (для противника):
> Противник находится в среде эксплуатации, располагает образцами СКЗИ, всеми руководствами и программами. 

Да, противнику в целом известно внутреннее устройство СКЗИ.

Но:
- известно до известных пределов (могут быть компоненты, например, датчики вскрытия корпуса, расположение которых не до конца документировано и меняется от образца к образцу);
- незащищенные отверстия -- это потенциальные дополнительные побочные каналы;
- незащищенные отверстия упрощают доступ "внутрь" в обход средств контроля.

При разработке пакета ФБ у нас была дискуссия относительно ФБ.4. Были варианты смягчения требования. Пока без смягчения. Давайте обсуждать дальше. Аргументированно. Никто не заинтересован во

> введение стандарта, которому затруднительно или невозможно соответствовать

Давайте только разберемся, почему невозможно. Разве отказ от прозрачных элементов корпуса и защита отверстий сеточками не обеспечивает выполнение ФБ.4?

**Comment by DKAndronchyk** [comment]
Дискуссии то и не получается...
Мне видится, что "отверстие защищённое сеточкой" есть "отверстие прозрачное в видимой части спектра". Предлагаю исключить комментарий к требованию, т.к. вместо уточнения получилось размытие.

**Comment by agievich** [comment]
Думаю, что примечание можно исключить. При условии, что будет найдена точная формулировка второй части требования. 

Суть второй части, на мой взгляд, состоит в следующем: визуальный осмотр СКЗИ не должен давать дополнительную информацию о КСК. Дополнительную по отношению к сведениям из конструкторской документации, в частности, информацию о текущем состоянии, о выполняемой операции и т.д.

Если мы согласимся с такой трактовкой второй части, то можно поискать формулировку.

**Comment by DKAndronchyk** [comment]
> Если мы согласимся с такой трактовкой второй части, то можно поискать формулировку.
Сложно согласится в принципе с форматом стандарта как профиля защиты. Но т.к. это не обсуждается, то отдельные формулировки несомненно требуют уточнения. В данном случае можно так и сформулировать:
"Визуальный осмотр СКЗИ не должен давать дополнительную (по отношению к сведениям из конструкторской документации) информацию о КСК,"

**Comment by agievich** [comment]
> Сложно согласится в принципе с форматом стандарта как профиля защиты.

Нет, не профиль защиты. Конечно нет. Здесь мы обсуждаем, рассматривая несколько вариантов требования. В стандарте, понятное дело,  будет  оставлен единственный вариант.

**Comment by agievich** [comment]
Предложения реализованы в #19. 
Туда же переносится обсуждение.
