### ISSUE TITLE
Энтропия

### ISSUE THREAD

**Issue by saverchenko** [bcrypto/skzi#2]
В п.5.6 СЧ.3 Указано, что если _в генераторе случайных чисел отсутствуют физические источники случайности, то должно использоваться **не менее двух** альтернативных разнотипных источников._ Регулятор понимает эту фразу буквально и требует наличие не менее двух источников энтропии и при генерации псевдослучайных чисел по СТБ 34.101.47-2017. Чтобы не было расхождения с приложением Г, где по 47 СТБ допускается один источник случайности, может быть в п.5.6 еще раз конкретизировать, что это требование не распространяется на алгоритмы генерации псевдослучайных чисел?

**Comment by zm1ca** [comment]
Действительно, для генерации псевдослучайных чисел данное требование не может быть применено. В то же время, одним из параметров, используемых при генерации псевдослучайных чисел согласно СТБ 34.101.47-2017 является секретный ключ, _одним из способов_ построения которого является обращение к _датчику случайных чисел_. В связи с этим, регулятор _предлагает_ добавлять альтернативный источник случайности при необходимости генерации указанного секретного ключа. На случаи генерации синхропосылок и прочих параметров криптографических алгоритмов, которые не обязательно должны быть получены случайным образом (в соответствии с ТНПА), требование использовать два источника случайности _не распространяется_.

Отметим отдельно, что реализация генератора случайных чисел и последующее обращение к нему, является лишь одним из допустимых способов построения ключа генерации псевдослучайных чисел. Так, например, возможна схема с генерацией ключа на внешнем устройстве и его транспортом в защищённую зону Вашего программного продукта.

**Comment by zm1ca** [comment]
Однако, важно также отметить, что уже поставлен вопрос о более подробном и не допускающем двойного толкования описании вопросов генерации случайных и псевдослучайных чисел, а также оценке качества источников случайности и методов обработки информации от них. Ясное понимание предъявляемых требований и предложений, несомненно в интересах регулятора.

**Comment by agievich** [comment]
Согласен с комментарием @zm1ca. Несколько пояснений общего характера.

1. ГСЧ рассматривается в СТБ 34.101.27 как универсальное устройство, выходные данные которого могут использоваться для построения как секретных объектов (ключи), та и несекретных (синхропосылки). Нет большого смысла отделять "секретные ГСЧ" от "несекретных". Да так никто и не делает.
2. Действительно, ключ алгоритма `brng-ctr` ∈ СТБ 34.101.47 можно либо сгенерировать с помощью ГСЧ, либо импортировать ("...схема с генерацией ключа на внешнем устройстве и его транспортом в защищённую зону" из комментария @zm1ca ).
3. При разработке СТБ 34.101.27 мы придерживались концепции "**требование как компромисс**". Я уже когда-то писал об этой концепции, повторю кратко применительно к ГСЧ.  Речь идет о том, что вопрос генерации случайных чисел в криптографических устройствах широк и глубок. Можно пойти по большому пути: классифицировать генераторы, детализировать их внутреннее устройство и функционирование, выдвинуть требования к каждому компоненту. Большой путь реализован в немецком стандарте AIS-31 (https://cosec.bit.uni-bonn.de/fileadmin/user_upload/teaching/15ss/15ss-taoc/01_AIS31_Functionality_classes_for_random_number_generators.pdf). Короткий путь (это и есть компромисс между регулятором и разработчиками) -- выдвинуть максимально лаконичные требования, которые возможно завышают планку безопасности и не позволяют добиться максимальной эффективности, но, тем не менее, просты в реализации. В нашем случае короткий путь -- это фактически три шага: 1) физический источник случайности или два разнотипных источника; 2) оценка энтропии источников и 3) криптографическая постобработка (с потенциальным снижением эффективности, но с сохранением гарантий безопасности при сбоях). На сегодняшний день, насколько я понимаю, имеются трудности только с реализацией шага 2.

Несколько слов про AIS-31. Актуальная редакция стандарта появилась в 2011 году (уже после введения в действие СТБ 34.101.27). На сегодняшний день AIS-31 является стандартом де-факто в Евросоюзе. При модернизации СТБ 34.101.27 безусловно следует учитывать положения AIS-31. Но не стоит переусердствовать, сохранив подход "требование как компромисс".

**Comment by agievich** [comment]
> ...Чтобы не было расхождения с приложением Г, где по 47 СТБ допускается один источник случайности.

Приложение Г к СТБ 34.101.47 полностью соответствует разделу 4.7 СТБ 34.101.27. Разрешений на один источник случайности в обоих случаях нет.

**Comment by saverchenko** [comment]
Как разработчика меня смущает, что в приложении Г к СТБ 34.101.47 и разделе 4.9 СТБ 34.101.27 говорится что: "Генератор использует ОДИН или несколько источников случайности (неопределенности, энтропии) и включает средства обработки данных от источников". Хоть далее и следует рекомендация, что: "Предпочтительным является использование физических источников случайности", но конкретно на необходимость использования ДВУХ нефизических источников в 47 СТБ указаний нет. Скорее всего недопонимание было и у других специалистов, т. к. вопрос о необходимости ДВУХ энтропий при генерации псевдослучайных чисел был поднят только в конце с.г. Если в новой редакции 27 СТБ конкретизировать это требование, то одним спорным моментом станет меньше. В любом случае решать Вам, а мы примем к исполнению любую редакцию.
