### ISSUE TITLE
"Внутренние компоненты" в пакете ФБ

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#229]
В пакете ФБ используются термины "внутренний компонент", "внутренний компонент СКЗИ", "внутренние КСК". Разнородная терминология вызывает вопросы (см. напр. #169).  Подразумеваются компоненты внутри криптографической границы СКЗИ? Или внутри самого СКЗИ? Исключая КСК или включая? 

Необходимо навести порядок с терминологией.

**Comment by rashchenia** [comment]
В пакете ФБ под "внутренними компонентами" понимаются компоненты (аппаратные, программные, программно-аппаратные), находящиеся внутри контролируемой границы, подлежащей физической защите. В терминах проекта стандарта это криптографическая граница. Что отражено в п. 4.2 проекта стандарта: 

> ...Первая цель - защита криптографической границы, отделяющей СКЗИ от среды (см. рис. 1). Направления защиты: 
> - физическая защита от проникновения... 

Для однозначного понимания предлагается в пакете ФБ термин "внутренний компонент" заменить на "компонент внутри криптографической границы СКЗИ".

**Comment by agievich** [comment]
В ФБ.4 слова "о внутренних КСК"  заменены на "о КСК".
