### ISSUE TITLE
Опечатки в тексте Стандарта

### ISSUE THREAD

**Issue by MaksimKazlovski** [bcrypto/skzi#23]
В ходе чтения проекта Стандарта было обнаружено несколько небольших орфографические и пунктуационных неточностей, которые не влияют на смысловое содержание документа:

1.  Подраздел 4.2.

> Системные компоненты как правило являются массовыми, предназначенными для широкого круга потребителей, и универсальными, не ориентированными на реализацию исключительно криптографических сервисов.

Согласно [правилам](https://pishugramotno.ru/punktuacia/kak-pravilo-vydelyaetsya-zapyatymi-ili-net), словосочетание "как правило" обычно выделяется запятыми.

2.  Пункт 5.3.2 (Примечание 1)

> Сеансовые копии не обязательно определять как отдельные объекты, достаточно обеспечить их очистку по завершении сеансов [ЗО.12].

Согласно [правилам](https://obrazovaka.ru/kak-pishetsya/neobyazatelno.html) в данном случае правильно писать "необязательно".

3.  Пункт 5.4.1

> Для очистки содержимого энергонезависимой памяти следует использовать многократную перезапись ячеек памяти битовыми строками с средним, малым и большим числом единиц.

Согласно [правилам](https://obrazovaka.ru/kak-pishetsya/s.html) следует писать "со средним".

4. Пункт 5.13.2 (Примечание 1)

> При возобновлении сеанса ключи защиты обновлять не обязательно.

Согласно [правилам](https://obrazovaka.ru/kak-pishetsya/neobyazatelno.html) в данном случае правильно писать "необязательно".

5. Пункт 5.13.2 (Примечание 3)

> Например, когда их генерирует удаленный оператор и пересылает в зашифровыванном на открытом ключе СКЗИ виде.

Правильно будет "зашифрованном", а не "зашифровыванном".

6. Приложение Б.4 (Пример 4)

> Еше раз изменим стратегию.

Правильно будет "еще", а не "еше".

7. Приложение В. 

> Оптимизатор не отключает бесполезную (на его взгяд) очистку.

Правильно будет "взгляд", а не "взгяд".

**Comment by agievich** [comment]
Реализовано в #19.
