### ISSUE TITLE
АУ.2: изменить или исключить примечание

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#232]
Примечание к АУ.2:

> Должны регистрироваться, в том числе, операции над журналом аудита.

Логика примечания: коль скоро журнал аудита является критическим объектом, то в соответствии с АУ.2, дефис 3, операции над журналом должны регистрироваться.

Если журнал аудита перестает быть критическим объектом (см. #28), то следует уточнить или исключить примечание.

**Comment by DKAndronchyk** [comment]
В случае, если журнал аудита остаётся критическим объектом (см.#28), предлагаю решение, аналогичное предложенному для #233

**Comment by agievich** [comment]
Предлагается следующая редакция примечания (без "должно быть"):

> **Примечание** -- Если журнал аудита отнесен к критическим объектам администратора, то операции над ним входят в перечень регистрируемых событий.
