### ISSUE TITLE
НС: примечания с "должно быть"

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#233]
Требования НС.1-3 сопровождаются примечаниями, которые содержат "должно быть":

>  При настройке операционной системы должна быть...

С одной стороны, примечания можно расценивать как требования (см. #33). С другой стороны, примечания можно считать продолжениями требований при фокусировке на операционной системе как части системной среды (в требованиях идет речь о настройке системной среды).

Следует провести ревизию способа подачи требований по настройке операционной системы, провести корректировку при необходимости.

**Comment by DKAndronchyk** [comment]
> С одной стороны, примечания можно расценивать как требования (см. #33). С другой стороны, примечания можно считать продолжениями требований при фокусировке на операционной системе как части системной среды (в требованиях идет речь о настройке системной среды).
> 
> Следует провести ревизию способа подачи требований по настройке операционной системы, провести корректировку при необходимости.

Вариант, при котором убираются сами примечания, а их текст вносится как продолжение соответствующего требования не рассматривается? 
Например, заменить текущую редакцию:
>Требование НС.1 (1–4). Должны быть определены настройки системной среды
для безопасной установки СКЗИ уполномоченным администратором.
Примечание 1 — При настройке операционной системы должна быть настроена политика
управления доступом, механизмы аутентификации. Должна быть определена группа операторов, которая имеет право устанавливать программы. Группа должна включать администраторов СКЗИ и только их.

на следующую:
Требование НС.1 (1–4). Должны быть определены настройки системной среды для безопасной установки СКЗИ уполномоченным администратором. При настройке операционной системы должна быть настроена политика
управления доступом, механизмы аутентификации. Должна быть определена группа операторов, которая имеет право устанавливать программы. Группа должна включать администраторов СКЗИ и только их.

**Comment by agievich** [comment]
Примечания с "должно быть" исключены. Содержание примечаний (с корректировками, см. #78) перенесено в преамбулу пакета НС в подаче "следует".
