### ISSUE TITLE
КП.2: ТНПА или СТБ

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#234]
В КП.2 требуется, чтобы спецификации криптографических алгоритмов списка [КП.1] были приняты  качестве ТНПА. Речь идет о технических нормативных правовых актах в области технического нормирования и стандартизации (см. раздел 2).

Ст. 26 Закона РБ О НПА 130-З от 17.07.2018 гласит:
> К техническим нормативным правовым актам в области технического нормирования и стандартизации относятся технические регламенты Республики Беларусь, технические кодексы установившейся практики, государственные стандарты Республики Беларусь, общегосударственные классификаторы Республики Беларусь, технические условия и стандарты организаций.

Таким образом, КП.2 разрешает использовать криптографические алгоритмы, установленные не только в СТБ, но и в ТК, ТР, ТУ, СО. До сих пор криптография вводилась преимущественно в  СТБ. Было только два исключения: руководящие документы Национального банка на алгоритм генерации псевдослучайных чисел и на протоколы формирования ключа. Алгоритм переместился в СТБ 34.101.47, а РД на протоколы так и остался проектом, который впрочем широко применялся.

Следует ли пресечь в КП.2 все варианты ТНПА, за исключением СТБ? 
Или разрешить использовать только те ТНПА, которые включены в определенные ТР?

**Comment by DKAndronchyk** [comment]
Считаю, что как минимум нужно уточнить, что речь идёт о ТНПА принятых в Республике Беларусь. Из текста Проекта явно не следует.

**Comment by agievich** [comment]
Аббревиатура ТНПА раскрыта в начале раздела 2. Подразумеваются исключительно документы, принятые в РБ.

Ссылка на ТНПА до сих пор работала без сбоев. Других разумных вариантов не найдено. Предлагается оставить КП.2 без изменений.
