### ISSUE TITLE
Средство аутентификации vs Механизм аутентификации

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#236]
В соответствии с https://github.com/bcrypto/skzi/issues/169#issuecomment-886822950 предлагается вместо "средство аутентификации" писать "механизм аутентификации".

**Comment by agievich** [comment]
"Средство" в связках "средство аутентификации", "средство безопасности" изменено на "механизм". Исключение составляет пакет ФБ, где требуется более тонкая терминологическая настройка.

**Примечание**. "Средство" сохранено в "технические средства противника", "средства контроля доступа операционной системы", "средства разработки и сборки программ" и в других случаях, там, где не идет речь о внутренних компонентах СКЗИ.

**Comment by rashchenia** [comment]
В пакете ФБ слово "средство" предлагается исключить. Вариант уточненной редакции преамбулы см. в #235. По тексту требований пакета ФБ слова "техническое средство контроля доступа" заменить словами "датчик контроля доступа".
