### ISSUE TITLE
Уровни: нужны непротиворечивые примеры СКЗИ

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/skzi#24]
Для обоснования выбранных уровней нужно привести примеры СКЗИ на каждом уровне. Существующие примеры (п. 4.3, стр. 8) вызывают вопросы:
 * уровень 1 - пример "типовое программное СКЗИ" - OK
 * уровень 2 - пример "ПО удостоверяющего центра" - противоречит определению уровня 2 в части двухфакторной аутентификации - требуется уточнить, где второй фактор
 * уровень 2 - пример "ПСКЗИ на облачных сервисах" - противоречит определению уровня 2 в части двухфакторной аутентификации - требуется уточнить про второй фактор. вторым фактором является пароль доступа к облаку?
 * уровень 2 - пример "ПС, загружаемое вместе с ОС с фиксированного установочного диска" - странное применение понятия двухфакторной аутентификации: вторым фактором является "обладание установочным диском"? установочный диск - "только для чтения"? тогда возникает вопрос сохранения состояния ПС, например состояния блокировки между операциям включения, смена пароля? 
 *  уровень 3 - пример "криптографический USB токен, ID-карта" -  опять же странное применение понятия двухфакторной аутентификации: вторым фактором является "обладание устройством, на которое осуществляется вход"?  Аудит на персональном СКЗИ (личной ID-карте) должен делать выделенный администратор? Обязателен аудит на ограниченном по памяти устройстве? при этом нужно аудировать события включение/выключение питания? тогда гарантировано попадание в состояние блокировки только в результате прикладывания карты к ридеру.
 *  уровень 3 - пример "аппаратный IP-шифратор" -  противоречит определению уровня 2 в части двухфакторной аутентификации - требуется уточнить про второй фактор
 *  уровень 4 - пример "аппаратное СКЗИ" -  противоречит определению уровня 2 в части двухфакторной аутентификации - вторым фактором опять же является "обладание устройством, на которое осуществляется вход"?

**Comment by agievich** [comment]
Требования пакета ИА (идентификация и аутентификация) выдвигаются не к СКЗИ, а к системной среде. Требования могут быть реализованы в самом СКЗИ, но в общем случае это не так. Стандартная схема, которая работает с 2007 года.

Предлагается пересмотреть список вопросов по 2FA с учетом сказанного. Несколько неожиданным является то, что вопросы посыпались после 10 лет применения текущей редакции СТБ, после того, как большое число ПСКЗИ прошли сертификацию по классу (уровню) 2, где требуется подтвердить 2FA.

Большинство вопросов требует пояснений. Например, последний вопрос. Да, в СКЗИ уровня 4 требуется 2FA. Чему это противоречит? 

Во многих случаях предлагается даже не ответить на вопрос, а подтвердить предположение, причем зачастую довольно неожиданное. Например предположение о том, что вторым фактором является владение установочным диском. Предлагается разбить тему на несколько частей, и представить каждую из них в более ясной форме.

По поводу администратора ID-карты. Здесь (однопользовательская система) администратором является сам владелец. Стандартная схема, которая действует с 2007 года.

По поводу аудита на микроустройствах. Да, это действительно следует тщательно обсудить. Пакет АУ остается довольно сложным. Конечно следует предусматривать обработку переполнения журнала, чтобы не было блокировок из-за переполнения. В этом был вопрос?

**Comment by andrewkostevich** [comment]
> Несколько неожиданным является то, что вопросы посыпались после 10 лет применения текущей редакции СТБ, после того, как большое число ПСКЗИ прошли сертификацию по классу (уровню) 2, где требуется подтвердить 2FA.

Они прошли сертификацию потому что являются аналогами приложения Б СТБ 34.101.27: являются единым СКЗИ, которое включает и программные компоненты, и аппаратные токены. В рассматриваемом Проекте произошло изменение концепции: программные компоненты и аппаратные токены рассматриваются как отдельные СКЗИ. Это и вызывает вопрос: как аппаратные токены, _рассматриваемые самодостаточными СКЗИ_, могут обеспечить 2FA (на 3+ уровне)? 

Попытка распространить понятные требования к ПСКЗИ на _аппаратные токены, рассматриваемые как самодостаточными СКЗИ_, сталкивается с проблемами:
 * как обеспечить 2FA - нет второго фактора
 * как обеспечить аудит - нет ресурсов для его ведения
 То, что может быть выполнено (и выполнялось) для ПСКЗИ с аппаратными токенами, очень проблемно 
переносится на чисто аппаратные токены.
 
Для сравнения в части 2FA: в FIPS 140-3 двухфакторная аутентификация требуется только на максимальном - пятом уровне.

**Comment by agievich** [comment]
> в FIPS 140-3 двухфакторная аутентификация требуется только на максимальном - пятом уровне

В FIPS 140-3 нет пятого уровня.

Обсуждение переносится в #26, #27.
