### ISSUE TITLE
СЧ.6: убрать ссылку на КП.1

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#240]
В требовании СЧ.6 предлагается убрать ссылку на КП.1. Другими словами, при криптографической обработке данных от источников случайности разрешить применять криптографические алгоритмы, не включенные в список КП.1. 

Напомним, что алгоритмы списка КП.1 должны быть установлены в ТНПА (КП.2). Отказ от ссылки на КП.1 позволит расширить перечень алгоритмов. Сейчас такой широко распространенный (и удобный для разработчиков) ГСЧ как Linux/dev/random в принципе не может соответствовать требованиям пакета СЧ из-за ссылки на КП.1 в СЧ.6. Ослабление СЧ.6 открывает возможность соответствия.

Основанием для ослабления СЧ.6 является заявленное в требовании назначение криптографических алгоритмов -- они 
> должны обеспечивать сложные зависимости между выходными данными генератора и данными от каждого из источников случайности.  

"Обеспечение сложных зависимостей" лишь весьма опосредованно связано с обеспечением "конфиденциальности, контроля целостности и (или) подлинности данных", объявленному в определении криптографического алгоритма. "Обеспечение сложных зависимостей" не контролируется при оценке стойкости алгоритмов перед их принятием в ТНПА. Поэтому настаивать на использовании алгоритмов из ТНПА нецелесообразно.

**Примечание**. Впрочем имеются аргументы против ослабления СЧ.6. Они вытекают из следующего комментария к СЧ.6 в преамбуле пакета СЧ:
> Более того, при правильной криптографической обработке генератор будет защищен от некоторых атак. Для защиты следует предусмотреть внутреннее состояние генератора. Оно обновляется по данным от источников и по нему строятся выходные случайные числа. Обновление следует организовать  так, что:
> - по случайным числам вычислительно трудно определить состояние;
> - по текущему состоянию трудно определить предыдущие случайные числа;
> - по текущему состоянию без данных от источников трудно определить будущие случайные числа;
> - по данным от источников без текущего состояния трудно определить будущие случайные числа [CЧ.6].

Комментарий носит характер рекомендаций по организации криптографической обработки в ГСЧ. Часть рекомендаций касается трудности обращения. Обращение -- это классическая криптографическая задача, трудность обращения контролируется в ТНПА на релевантные криптографические алгоритмы (напр., хэширования) и этот контроль делает ссылку на КП.1 в СЧ.6 частично оправданной (правда через довольно запутанную логику и без связи с обращением).

**Comment by agievich** [comment]
Предлагается обсудить на конференции https://github.com/bcrypto/skzi/projects/1#card-67128204.

**Comment by agievich** [comment]
Ссылка на КП.1 исключена.

**Comment by DKAndronchyk** [comment]
> Ссылка на КП.1 исключена.

В версии 3.3 пока присутствует. Исключена в следующей?

**Comment by agievich** [comment]
> В версии 3.3 пока присутствует. Исключена в следующей?

Устранена (https://github.com/bcrypto/skzi/commit/39551326f0c18cd91ccdfba2b9016de134a2ca9e) в версии 3.31 (https://github.com/bcrypto/skzi/releases/tag/v3.31).

**Comment by agievich** [comment]
Решение пересмотрено по результатам совещания https://github.com/bcrypto/skzi/projects/1#card-69845894: ссылка на КП.1 сохранена.
