### ISSUE TITLE
Перенести НС.7 в пакет ПР

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#244]
Требование НС.7
> Операционная система должна входить в состав СКЗИ.

слабо касается настройки среды. Целесообразно перенести требование в пакет ПР.

Одновременно предлагается изменить требование, изложив его в следующей редакции

> В состав СКЗИ должно быть {ПР.1} включено программное обеспечение КСК.

и снабдив следующим примечанием:

> Включение программного обеспечения в состав СКЗИ означает взятие его под контроль -- тестирование {ПИ.3} и анализ исходных текстов {АП.4}. Операционная система, если она имеется, также подпадает под контроль.  Речь может идти о специализированной системе  собственной разработки или об облегченной универсальной (встраиваемой, embedded) системе с открытым кодом.

О

**Comment by DKAndronchyk** [comment]
> и снабдив следующим примечанием:
> 
> > Включение программного обеспечения в состав СКЗИ означает взятие его под контроль -- тестирование {ПИ.3} и анализ исходных текстов {АП.4}. Операционная система, если она имеется, также подпадает под контроль.  Речь может идти о специализированной системе  собственной разработки или об облегченной универсальной (встраиваемой, embedded) системе с открытым кодом.

В такой редакции практически исключается вариант использования разработчиком СКЗИ сторонних ОС с закрытым кодом. Хотя в теории на практике разработчик СКЗИ может договорится на коммерческой основе использовать в своём продукте проверенную чужую ОС, возможно, даже имеющую сертификат соответствия на ТР РБ 027.
Предлагаю вместо:
или об облегченной универсальной (встраиваемой, embedded) системе с открытым кодом
Писать:
, об облегченной универсальной (встраиваемой, embedded) системе с открытым кодом и пр.

**Comment by agievich** [comment]
В целом предложение принимается. Новая редакция примечания:

> Включение программного обеспечения в состав СКЗИ означает взятие его под контроль -- тестирование {ПИ.3} и анализ исходных текстов {АП.4}. Операционная система, если она имеется, также подпадает под контроль. Речь может идти о специализированной системе собственной разработки или об облегченной универсальной (встраиваемой, embedded) системе с открытым кодом.

**Примечание**. 
> Хотя в теории на практике разработчик СКЗИ может договорится на коммерческой основе использовать в своём продукте проверенную чужую ОС, возможно, даже имеющую сертификат соответствия на ТР РБ 027.

Именно об этом я говорил в https://github.com/bcrypto/skzi/issues/97#issuecomment-904939265.
