### ISSUE TITLE
Перенести пакеты ФБ, ЗВ, ЗУ в раздел  "Функциональные требования к системной среде"

### ISSUE THREAD

**Issue by Karevik** [bcrypto/skzi#247]
В связи с тем, что установленные  в пакетах:
Физическая безопасность (ФБ)
Защита от воздействий (ЗВ)
Защита от утечек (ЗУ)
требования не имеют отношения к криптографическим сервисам предлагаю перенести из в раздел "Функциональные требования к системной среде".

**Comment by Karevik** [comment]
Если следовать Вашей логике:
> Пакеты ФБ, ЗВ, ЗУ касаются механизмов безопасности СКЗИ.

то пакеты Идентификация и аутентификация (ИА) и Настройка среды (НС) не касаются механизмов безопасности СКЗИ. 
Или это просто путаница, возникающая от попытки совмещения в одном документе требований к программным и программно-аппаратным СКЗИ? 
Ведь для программного СКЗИ системная среда находится вокруг СКЗИ, а для программно-аппаратного - внутри СКЗИ. При том, что требования ИА и НС обязательны для СКЗИ любого уровня.
Тогда было бы логичнее  ограничить применение требований  ИА и НС только на 1 и 2 уровнях?

**Comment by agievich** [comment]
> Ведь для программного СКЗИ системная среда находится вокруг СКЗИ, а для программно-аппаратного - внутри СКЗИ.

В основном да, но в общем случае ситуация сложнее: для некоторых аппаратных СКЗИ системная среда может быть за пределами средства. Пример: криптографическая плата для ПК. Еще раз повторю (см. #43), что дихотомия "программное СКЗИ vs аппаратное" работает плохо или, точнее, не всегда коррелирует с уровнем защиты. Поэтому создавать два стандарта (так можно понять последнее замечание) -- один на программные средства, другой на аппаратные -- представляется нецелесообразным и даже некорректным.

> При том, что требования ИА и НС обязательны для СКЗИ любого уровня. 

Все верно. Другое дело, что требования к среде могут быть переадресованы СКЗИ. Об этом сказано в п.  4.1:
> СКЗИ использует ресурсы системной среды, безопасность средства зависит от работоспособности и надежности компонентов среды. Поэтому функциональные требования выдвигаются как к СКЗИ, 
так и к его системной среде. 

> Если системные компоненты не входят в состав СКЗИ, как в случае программного средства, то требования к среде адресуются потребителю СКЗИ. Потребитель настраивает среду для безопасного применения средства. Однако если некоторый системный компонент включен в состав СКЗИ, то требования, его касающиеся, реализуются самим СКЗИ и, таким образом, адресуются разработчику.
