### ISSUE TITLE
Классификация ID-карты

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/skzi#25]
С учетом массового внедрения ID-карты желательно оценить применимость проекта стандарта к ID-карте.

Владельцу на руки выдается:
 * ID-карта согласно СТБ 34.101.79, реализующая операции с личными ключами (выработка ЭЦП/транспорт ключа/аутентификация)
 * PKCS#11 библиотека согласно СТБ 34.101.78, реализующая криптографические алгоритмы с открытыми и секретными ключами, вычисление хэш-значения
 * AdES библиотеки согласно СТБ 34.101.80, СТБ 34.101.81, СТБ 34.101.82, реализующие формирование электронных документов
 * ATTR библиотека согласно СТБ 34.101.67, реализующая управление полномочиями владельца ID-карты
 * клиентская программа ID-карты, реализующая протоколы BPACE, BAUTH, TLS и осуществляющая управление PINами от ID-карты. Использует или PKCS#11 библиотеку согласно СТБ 34.101.78 или другую реализацию криптографических алгоритмов.
 * клиентская программа для управления сертификатами открытых ключей, списками отозванных сертификатов, атрибутными сертификатами согласно СТБ 34.101.19, согласно СТБ 34.101.78, .... Использует или PKCS#11 библиотеку согласно СТБ 34.101.78 или другую реализацию криптографических алгоритмов.
 
Все в совокапности функционирует
 * на персональном компьютере под управлением массовой операционной системы с обычными (по умолчанию) настройками безопасности
 * на смартфоне под управлением обновляющихся операционной системы Android/iOS с настройками безопасности по умолчанию + доступ к системным критическим компонентам блокируется ОС + нет выделенного администратора, отличного от пользователя 
 * на смартфоне под управлением необновляющихся устаревших версий операционной системы Android (4.4-10.0) с настройками безопасности по умолчанию + доступ к системным критическим компонентам блокируется ОС + нет выделенного администратора, отличного от пользователя (уровень 1-?)

Это является единым СКЗИ в рамках приказа ОАЦ 77. На какой уровень может быть отнесено такое СКЗИ, чтобы хотя бы определить перечень требований к нему?

**Comment by agievich** [comment]
Позиционирование ID-карты со всеми перечисленными компонентами как единого СКЗИ не кажется логичным. Да, так можно делать, но потом придется разбираться со схоластическими вопросами. 

Обсуждаемый проект стандарта, наоборот, склонен к выделению отдельных самодостаточных СКЗИ, которые могут обмениваться объектами (например, хэш-значениями) в системной среде (в вопросе перечислено несколько примеров сред) и которые управляются клиентскими программами (в вопросе перечислено несколько примеров КП). Даже если КП реализует криптографическую логику, это все равно клиентская программа при условии, что логика обслуживает взаимодействие с СКЗИ, а не является самостоятельной криптографической услугой (сервисом).

**Comment by andrewkostevich** [comment]
> Позиционирование ID-карты со всеми перечисленными компонентами как единого СКЗИ не кажется логичным. 

Это состав СКЗИ, требуемый приказом ОАЦ 77. По сути это тоже является является единым СКЗИ:
 * выдается пользователю единым комплектом
 * эксплуатируется единым комплектом
 * является самодостаточным
 * удаление одной из компонент ведет к потере некоторого или всего функционала

> Обсуждаемый проект стандарта, наоборот, склонен к выделению отдельных самодостаточных СКЗИ

В такой концепции "самодостаточные СКЗИ" будут иметь малый ограниченный набор функций. Это будет противоречить концепции приказа ОАЦ 77:  Приказ 77 фиксирует минимальный набор требований к СКЗИ и он достаточно широкий: обязательные криптонаборы + протоколы + форматы электронных документиов + управление сертификатами... 
Не факт, что такое "самодостаточное СКЗИ" в понятии Проекта СТБ окажется СКЗИ в понятии Приказа 77 - это требует выверки.

IMHO, трудности в классификации ID-карты с комплектом ПО как единого СКЗИ + противоречие с Приказом ОАЦ 77 указывает на проблемы в концепции стандарта.

**Comment by DKAndronchyk** [comment]
> IMHO, трудности в классификации ID-карты с комплектом ПО как единого СКЗИ + противоречие с Приказом ОАЦ 77 указывает на проблемы в концепции стандарта.

Горячо поддерживаю эту озабоченность. И речь не только про ID карты, а в целом про расхождения в идее/концепции. FIPS 140 и проект СТБ 34.101.27 созданный по его мотивам определяют требования к  криптомодулю, т.е. в общем случае несамостоятельному элементу некой более широкой системы. А регулятор оперирует и предъявляет требования к самодостаточным СКЗИ. Незначительные различия в стартовых смыслах могут и уже приводят к сложно разрешимым противоречиям в итоге.

**Comment by agievich** [comment]
>  FIPS 140 и проект СТБ 34.101.27 созданный по его мотивам

Очередное неожиданное утверждение. Напомню, что проект СТБ 34.101.27 создан по мотивам СТБ 34.101.27-2011, который в свою очередь создан по мотивам СТБ П 34.101.27-2007, который в свою очередь создан в парадигме Общих критериев и да, действительно, под влиянием FIPS 140. 

Хорошо, согласимся на минуту с @DKAndronchyk. Пусть проект СТБ 34.101.27 создан по мотивам FIPS 140. Согласимся с @andrewkostevich, что у СТБ 34.101.27 есть проблема с концепцией. Согласившись два раза, мы приходим к выводу, что и у FIPS 140 есть проблема с концепцией. Хорошо, есть проблема с концепцией. Чтобы разобраться с проблемой, нужно выслушать альтернативную концепцию. В чем она состоит? @andrewkostevich 

Если говорить о концепции проекта, то суть дела в следующем:
1. Отличительным признаком СКЗИ является реализация криптографических сервисов.
2. Сервисы доступны оператору напрямую (клавиатура, мышь, кнопки) или через клиентские программы.
3. ID-карта соответствует определению СКЗИ: она реализует криптографические сервисы, эти сервисы доступны оператору через клиентские программы.
4. Перечисленный в самом начале комплекс программ вместе с ID-картой также соответствует определению СКЗИ: снова реализует криптографические сервисы,  сервисы доступны оператору либо напрямую, либо через клиентские программы.

Комплекс программ вместе с ID-картой как СКЗИ -- это возможно, но не очень здорово. ID-карта перестает быть универсальной, теряется гибкость, усложняется сопровождение, обновление. Плюсом для разработчика может быть только привязка ID-карты к собственным проприетарным программам. Если такая привязка является целью, то да, нужно позиционировать ID-карту как часть комплекса. Если нет, то следует позиционировать как отдельное аппаратное СКЗИ.

**Comment by agievich** [comment]
Вопрос закрывается. Будет открыт заново, если появятся конкретные предложения от @andrewkostevich.
