### ISSUE TITLE
Защита объектов: системные методы

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#251]
Операционная система или системная среда в целом могут иметь в своем составе подсистему, которая обеспечивает защиту ключей при хранении и контролирует доступ к ним обслуживаемых программ, включая программы СКЗИ. Речь идет о системных методах защиты объектов. Предлагается разрешить использовать системные методы на уровне 1.

Простейшим системным методом защиты является настройка прав доступа к файлам с ключами. Защита легко обходится, если у противника есть доступ к файлам в обход операционной системы. Но на уровне 1 у противника нет достаточного потенциала для такого доступа (см. таблицу 2).

Набросок реализации предложения:

1. В преамбуле пакета ЗО объявить системные методы:

> 9. Системные методы. Состоят в обеспечении конфиденциальности и контроле целостности объектов, которые хранятся в пределах криптографической границы, средствами системной среды. Простейшим методом защиты является настройка прав доступа к объектам (файлам с объектами): доступ может получить только владелец объекта и только после успешной аутентификации. Более сложные методы включают аутентифицированное шифрование объектов на специальных ключах системной среды.

2. В ЗО.1 и ЗО.2 добавить предложение: 
> На уровне 1 при защите объектов во время хранения список дополняется системными методами. 

3. Добавить новое требование (со сдвигом номеров последующих требований):

> **Требование ЗО.9 (1)**. Должны быть определены и обоснованы системные методы защиты объектов при хранении (todo: содержание обоснования).

**Comment by azhmakov** [comment]
Если имеем СКЗИ 2-го уровня, выполненное программно, то как в принципе обеспечить защиту объекта "исполняемый программный модуль", если не системными методами?
