### ISSUE TITLE
Программные vs Программно-аппаратные СКЗИ: варианты

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#257]
В Проекте дихотомия "программные СКЗИ vs программно-аппаратные" проводится по составу: если в состав СКЗИ входят аппаратные компоненты, значит программно-аппаратное / аппаратное / аппаратно-программное средство, не входят -- программное.

При таком подходе программно-аппаратное средство не обязательно надежнее программного. Проект допускает ситуации, когда программное средство соответствует уровню 2, а аппаратное -- только уровню 1. Но такая ситуация противоречит сложившейся практике, согласно которой программно-аппаратные СКЗИ заведомо надежнее программных. Эта практика отражена в действующих нормативных документах, которые впрочем не сопровождаются строгими определениями терминов "{программное|аппаратное} СКЗИ".

В Проекте сделана попытка учесть сложившуюся практику -- через примечание

> Имеется практика деления СКЗИ на программные и программно-аппаратные не по составу, как в настоящем стандарте, а по гарантиям безопасности. Согласно этой практике, программно-аппаратные средства считаются более защищенными, именно их требуется использовать для защиты служебной информации ограниченного распространения. Настоящий стандарт вводит явное деление по уровням 
безопасности, при котором для защиты служебной информации следует использовать СКЗИ уровней 3 и 4. 

Предложенное решение, назовем его **вариант A**, не всех устраивает. Предложены мягкие отступления от варианта A, и принципиальные отступления. Предложенные отступления кратко обсуждаются далее.

**Вариант A1**. Убрать примечание.

**Вариант A2**. Сделать примечание более весомым, подняв его на уровень основного текста.

**Вариант B1** (https://github.com/bcrypto/skzi/issues/43#issuecomment-901812754). Изменить определение программно-аппаратного средства: использовать характеризационные признаки "выполненное в виде аппаратного устройства" и "основным предназначением которого является выполнение криптографических сервисов."

**Вариант B2** (https://github.com/bcrypto/skzi/issues/43#issuecomment-904478219). Изменить определение программно-аппаратного средства: использовать характеризационный признак "в котором криптографические сервисы реализованы аппаратно и/или с использованием программно-аппаратных средств."

**Вариант B3** (https://github.com/bcrypto/skzi/issues/106#issue-931373118). Изменить определение программно-аппаратного средства: использовать характеризационный признак "firmware" в стиле СТБ ИСО/МЭК 9126-2003 ("технические средства, содержащие компьютерную программу и данные, 
которые не могут изменяться средствами пользователя"). 

**Вариант C** (https://github.com/bcrypto/skzi/issues/189#issue-943729421). Существенно повысить требования к программно-аппаратным средствам. Характеризационные признаки (краткий пересказ):
- прямая (без ОС) работа с аппаратными ресурсами;
- изолированные аппаратные ресурсы;
- немодифицируемое ПО;
- нет лишнего функционала;
- пользователи не могут изменять настройки, влияющие на безопасность.

Предлагается обсудить варианты, возможно расширив их список, и, в конце концов, выбрать один из них.

**Comment by enigmaby** [comment]
Для того, чтобы строго разграничить понятия "программно-аппаратные" и "программные" средства криптографической защиты информации, необходимо внести определенность в чем разница между работой программы, реализующей фунции СКЗИ, работающей под управлением операционной системы на аппаратной платформе, от той же программы, реализующей те же фунции СКЗИ и работающей непосредственно с аппаратной платформой напрямую, минуя "абстрактных посредников". Данное понимание начинает появляться с примечания к определению понятия "операционная система" в проекте стандарта с введения термина "технология "bare machine"". Исходя из этого понятия, предлагаем дать определение "программно-аппаратным" средствам и их производным ("аппаратное", "аппаратно-программные") следующим образом: 
"Средство криптографической защиты информации, в состав которого входят аппаратные компоненты для программной реализации системных компонент СКЗИ исключительно по технологии "bare machine"".

**Comment by EAFedorov** [comment]
Мне кажется, что некий HSM модуль может появиться и на уровне 2. Он будет состоять из "стандартного железа" и не иметь уникальных критических системных компонент. Это будет программное средство + услуга по подбору аппаратной платформы. И такое средство может быть вполне востребованным в информационных системах класса 3-юл, 3-фл. А вот требования должны исключить возможность сертификации такого средства на класс 3 и выше.
Может в определение так и указывать, что-то вроде:

> **аппаратное (аппаратно-программное, программно-аппаратное) средство криптографической защиты информации:** Средство криптографической защиты информации, соответствующее требованиям класса 3 и выше данного Стандарта.

А уже орган по сертификации должен при получении заявки на сертификацию отклонять заявки средств, имеющие в своем названии сочетание "программно-аппаратное" и заявляемое на класс 2 и ниже.
В таком случае программные средства + услуга по подбору аппаратной платформы смогут пройти сертификацию и иметь название вроде "Устройство криптографической защиты информации" и не будут допущены для защиты информации ДСП.

**Comment by agievich** [comment]
Оформил предыдущие предложения в виде двух дополнительных вариантов:

**Вариант B4** (https://github.com/bcrypto/skzi/issues/257#issuecomment-940765615). Изменить определение программно-аппаратного средства:
> Средство криптографической защиты информации, в состав которого входят аппаратные компоненты для программной реализации системных компонент СКЗИ исключительно по технологии "bare machine".

**Вариант B5** (https://github.com/bcrypto/skzi/issues/257#issuecomment-940964046). Изменить определение программно-аппаратного средства:
> Средство криптографической защиты информации, соответствующее требованиям класса 3 и выше данного Стандарта.

**Comment by MaksimKazlovski** [comment]
Предлагается дополнительно рассмотреть следующий вариант определения данного термина:

> аппаратное (аппаратно-программное, программно-аппаратное) средство криптографической защиты информации: Средство криптографической защиты информации, которое запрещает загружать, устанавливать, исполнять и интерпретировать как программный код входные данные, полученные в процессе эксплуатации.

**Comment by agievich** [comment]
Результаты голосования на конференции https://github.com/bcrypto/skzi/projects/1#card-70669358:

![issue257](https://user-images.githubusercontent.com/5767055/137344812-2bb35e60-436c-43cd-9ef9-aab8cbe9195d.jpg)
