### ISSUE TITLE
Формулировка требования АУ.1

### ISSUE THREAD

**Issue by rashchenia** [bcrypto/skzi#265]
В АУ.1 имеется обратная ссылка на УД.3: "Журнал должен быть отнесен {УД.3} к объектам администратора". УД.3 определяет требования к политике управления доступом. Требования к объектам СКЗИ, включая указание владельца объекта, определены в УД.2. Возможно, более корректно заменить ссылку на УД.3 ссылкой на УД.2.

**Comment by agievich** [comment]
Предложение принято: cсылка на УД.3 изменена на УД.2. Реализовано в https://github.com/bcrypto/skzi/commit/e37c87681e3f01bfe5c18ee26f360829c0971c98.
