### ISSUE TITLE
Опечатка в требовании СЧ.6

### ISSUE THREAD

**Issue by Karevik** [bcrypto/skzi#267]
Имеется:
> Внутреннее состояние генератора, если оно используется, должно быть отнесено {УД.3} к критическим объектам.

Должно быть:
> Внутреннее состояние генератора, если оно используется, должно быть отнесено {**УД.2**} к критическим объектам.

**Comment by agievich** [comment]
Опечатка устранена в https://github.com/bcrypto/skzi/commit/cdec0304e30d1800065e2beebc7214a793d6b6dd.
