### ISSUE TITLE
ЗО.1 vs ЗО.15

### ISSUE THREAD

**Issue by DKAndronchyk** [bcrypto/skzi#270]
В СТБ 34.101.27-2020 есть не совсем понятная и, возможно цикличная конструкция :
Требование ЗО.1 (1–4). Должна обеспечиваться конфиденциальность критических объектов [УД.2]. Используемые для этого методы защиты должны выбираться из следующего списка: криптографические, аппаратные, разделения секрета. При защите частичных секретов список дополняется организационными мерами. На уровне 1 при защите объектов во время хранения список дополняется системными методами.

Из этого требования следует, что для СКЗИ 1-го уровня можно выбрать из списка только системный метод защиты объектов. Но далее: 
Требование ЗО.15 (1). Должны быть определены и корректно использованы системные методы защиты. Применение системных методов должно быть поддержано {НС.2} при настройке системной среды. Перед применением системного метода к критическому объекту [УД.2] он должен быть зашифрован на ключе, построенном по паролю владельца. Для шифрования и построения ключа должны использоваться криптографические алгоритмы из перечня [КП.1].

**Comment by agievich** [comment]
>Из этого требования следует, что для СКЗИ 1-го уровня можно выбрать из списка только системный метод защиты объектов.

Нет, не следует. Системный метод защиты является дополнительным к трем основным.

О цикличности. Если подразумевается, что в ЗО.15 системный метод строится с помощью криптографических алгоритмов и, поэтому не отличается от криптографического метода, то это не так. В системном методе ключ защиты строится по паролю (слабому секрету), в криптографическом методе -- генерируется по правилам соответствующей спецификации (КП.3), например, с помощью ГСЧ (СЧ.1).

**Comment by DKAndronchyk** [comment]
> В системном методе ключ защиты строится по паролю (слабому секрету), в криптографическом методе -- генерируется по правилам соответствующей спецификации (КП.3), например, с помощью ГСЧ (СЧ.1).

Не очень понятно - откуда следует такая связка? Построение ключа защиты по паролю - определённый в действующем ТНПА алгоритм. Зашифрование на таком ключе является самостоятельно криптографическим методом. Где-то присутствуют ограничения по его использованию для выработки ключа для семейств belt или bash?

**Comment by agievich** [comment]
В вводных частях СТБ 34.101.31, СТБ 34.101.77 есть требования о надежной генерации ключей.

Построение ключа по паролю -- это исключение из правил. Да, алгоритмы Belt продолжают использоваться, но, поскольку правила нарушены, результирующий механизм не обладает должной криптографической стойкостью и не может претендовать на звание криптографического метода защиты.

Кстати, в СТБ 34.101.45 определение механизма определения ключа по паролю сопровождается следующим комментарием:

> Владелец личного ключа должен оградить доступ других лиц даже к защищенному ключу. Тем не менее, угроза такого доступа существует, и парольная защита организуется так, чтобы максимально затруднить определение ключа без знания пароля.
