### ISSUE TITLE
ЗО.2 для ВСЕХ объектов?

### ISSUE THREAD

**Issue by DKAndronchyk** [bcrypto/skzi#271]
Требование ЗО.2 (1–4). Должен осуществляться контроль целостности и подлинности критических и открытых объектов [УД.2]. Используемые для этого методы защиты   должны выбираться из следующего списка: криптографические, аппаратные, алгоритмические. На уровне 1 при контроле целостности объектов во время хранения список  дополняется системными методами.

Требование ЗО.2 подразумевает, что для ВСЕХ открытых и ВСЕХ критических объектов СКЗИ осуществляется контроль целостности и подлинности? Из требований ЗО.3-ЗО.8 следует, что подлинность можно обеспечить применением только криптографических и аппаратных (видимо, аппаратных СКЗИ, где тоже используется криптография) методов. Если предположение что «ВСЕХ» верно, то выходит, что, например синхропосылку при пересылке между СКЗИ следует подписывать ЭЦП. Верно?

**Comment by agievich** [comment]
> Требование ЗО.2 подразумевает, что для ВСЕХ открытых и ВСЕХ критических объектов СКЗИ осуществляется контроль целостности и подлинности?

Да, для всех объектов, включенных в перечень [УД.2]. Но включать в перечень синхропосылки, имитовставки, подписи совсем необязательно. Совсем наоборот. Понятно, что рекурсия "обеспечить контроль целостности контрольной суммы" ни к чему хорошему не приведет. 

Кстати, с синхропосылкой проблем нет: имитовставка, вычисленная по любой из схем encrypt-then-mac или mac-then-encrypt,  поддерживает в том числе контроль целостности синхропосылки, использованной при зашифровании.
