### ISSUE TITLE
Системные объекты для программного СКЗИ

### ISSUE THREAD

**Issue by DKAndronchyk** [bcrypto/skzi#272]
В п.5.3.1 СТБ 34.101.27 есть пояснения термина «объект»:
 У объектов есть владельцы. Администратор может владеть журналом аудита, пользователь — ключами. Владелец может быть один (пример: личный ключ), их может быть два (секретный ключ парной связи) или несколько (журнал во владении группы администраторов). Файлы программ и конфигураций относятся к системным объектам, владельцем которых является системный оператор {УД.2}.

Правильно ли я понимаю, что в общем случае программного СКЗИ владельцем всех файлов СКЗИ является системный оператор и они не подпадают под требования СТБ 34.101.27 в качестве объектов СКЗИ (УД.2)? Для того, чтобы считать какие-то файлы открытыми объектами СКЗИ следует ограничить доступ к ним со стороны системного оператора, что в случае чисто программного СКЗИ не совсем понятно как. Верно?

**Comment by agievich** [comment]
> Правильно ли я понимаю, что в общем случае программного СКЗИ владельцем всех файлов СКЗИ является системный оператор и они не подпадают под требования СТБ 34.101.27 в качестве объектов СКЗИ (УД.2)? 

Правила владения определяет разработчик СКЗИ. Если в вопросе под "файлами СКЗИ" понимаются исполнимые файлы, скрипты, файлы настроек и др., которые не касаются какого-то конкретного явного оператора, то да, такие файлы разумно относить к системным.

> Для того, чтобы считать какие-то файлы открытыми объектами СКЗИ следует ограничить доступ к ним со стороны системного оператора, что в случае чисто программного СКЗИ не совсем понятно как. Верно?

Вопрос не до конца понятен. "Ограничить доступ" -- это отсылка к пакету УД. В этом пакете определяются требования к механизмам управления доступом, **реализованными в СКЗИ**. СКЗИ должно быть построено так, что его пользователь не имел доступа к сервисам администратора, чтобы пользователь A не мог сгенерировать ключ и выдать его за ключ пользователя B и так далее. Понятно, что неявный системный оператор может иметь прямой доступ к объектам операторов СКЗИ и поэтому системный оператор должен быть доверенным. Но это другая история. Она разворачивается в пакетах, посвященных требованиям к системной среде.
