### ISSUE TITLE
Уточнение системных методов защиты

### ISSUE THREAD

**Issue by DKAndronchyk** [bcrypto/skzi#273]
**п.5.4.1**
_6. Системные методы. Состоят в обеспечении конфиденциальности и (или) контроле целостности объектов, которые хранятся в пределах криптографической границы, средствами системной среды. Простейшим методом защиты является настройка прав доступа к объектам (файлам с объектами): доступ может получить только владелец объекта и только после успешной аутентификации._
Если в системе настроены права доступа к файлам для системного оператора (а они настроены всегда и во всех системах - ведь не уточняется какие они должны быть) это будет считаться что обеспечена конфиденциальность объектов? И где здесь контроль целостности? Или это можно реализовать другими настройками?

**Comment by agievich** [comment]
> Если в системе настроены права доступа к файлам для системного оператора (а они настроены всегда и во всех системах - ведь не уточняется какие они должны быть) это будет считаться что обеспечена конфиденциальность объектов?

Верно, если заменить "системный оператор" на "владелец", убрать скобки и учесть, что в соответствии с ЗО.15 критический объект даже при хранении в персональной локации должен дополнительно защищаться на пароле владельца.

> И где здесь контроль целостности? Или это можно реализовать другими настройками?

Контроль целостности файлов поддерживается во многих файловых системах.
