### ISSUE TITLE
Как определить СКЗИ?

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#3]
В действующей редакции СТБ 34.101.27 дано следующее определение:

> СКЗИ: Набор аппаратно-программных компонентов, который реализует криптографические алгоритмы и протоколы, а также возможно дополнительные средства управления ключами, контроля доступа и проверки работоспособности, предназначенные для безопасного управления вызовами криптографических алгоритмов и их входными и выходными данными.

В этом определении акцент сделан на криптографию. Реализация криптографии – это существенный отличительный признак СКЗИ. Остальные признаки (управление ключами, контроль доступа, проверка работоспособности) являются вспомогательными.

Но является ли выбранный признак единственным существенным? Другими словами, может ли средство (*набор аппаратно-программных компонентов*) реализовывать криптографию, и при этом не быть СКЗИ?

Три примера.

1. Процессор Intel. Процессор реализует команду `rdrand`. Данные от источника теплового шума обрабатываются криптографическим алгоритмом AES-CBC-MAC. Покупая процессор, вы покупаете аппаратное средство, реализующее криптографический алгоритм. Но вы не имеете доступ к реализации. Удовлетворят ли процессор определению? Да. Является ли он СКЗИ? Нет.

2. Процессор Intel с расширением AES-NI (ускоритель AES). Вы имеете доступ к командам AES-NI, но не пользуетесь ими. Является ли процессор СКЗИ? Нет.

3. Система управления версиями Git. В Git для контроля изменений файлов они хэшируются с помощью криптографического алгоритма SHA-1. Алгоритм SHA-1 был выбран как удобный метод расчета контрольных сумм. Могли бы выбрать некриптографический алгоритм хэширования (в стиле CRC), но выбрали криптографический. Является ли Git СКЗИ? Нет.

Во всех примерах криптография реализована. Но она либо недоступна, либо доступна и не используется, либо непрофильна. Подобные примеры надо учесть в определении СКЗИ. При этом определение нельзя перегружать.

Еще одна проблема определения (и всего текста СТБ 34.101.27 в целом) -- словосочетание "криптографические алгоритмы и протоколы". Его приходится многократно повторять. Словосочетание можно упростить, если "протоколы" определить как "интерактивные алгоритмы". Именно так сделано в СТБ 34.101.66.

**Comment by agievich** [comment]
## Предлагаемое решение

Во-первых, "алгоритмы и протоколы" можно сократить до "алгоритмы", если "протоколы" определить как в СТБ 34.101.66.

Во-вторых, признак "реализует криптографические алгоритмы" можно изменить на признак "реализует криптографические сервисы". Сервисы –  это, по определению, функции СКЗИ, предоставленные операторам (пользователям и администраторам).

Решение неудачное: СКЗИ определяется через свои собственные сервисы.  Циклическая ссылка. 

Можно по-другому: "реализует ... для внешнего использования". Суть сохраняется, а циклической ссылки удается избежать. 

**Реализация**:

> криптографический протокол: Интерактивный криптографический алгоритм, который выполняют несколько сторон-участников, обмениваясь между собой сообщениями, содержащими промежуточные результаты вычислений.

> СКЗИ: Набор аппаратно-программных компонентов, который реализует криптографические алгоритмы для внешнего использования. СКЗИ может реализовывать также функции управления ключами, контроля доступа и проверки работоспособности, предназначенные для безопасного управления вызовами криптографических алгоритмов и их входными и выходными данными.

**Comment by zm1ca** [comment]
> Во-первых, "алгоритмы и протоколы" можно сократить до "алгоритмы", если "протоколы" определить как в СТБ 34.101.66.

Предложение поддерживается, так как это действительно может упростить чтение.

Предлагаем использовать определение СКЗИ, приведённое в Указе Президента РБ от 09.12.2019 №494 (Глава 6). Это гарантирует "полноценность" СКЗИ по определению, так как переносит акцент с криптографических алгоритмов на прочие функциональные возможности.

**Comment by zm1ca** [comment]
средства криптографической защиты информации – программные, программно- аппаратные средства, реализующие один или несколько криптографических алгоритмов (шифрование, выработка и проверка электронной цифровой подписи, хэширование, имитозащита) и криптографические протоколы, а также функции управления криптографическими ключами и функциональные возможности безопасности;

**Comment by agievich** [comment]
> средства криптографической защиты информации – программные, программно- аппаратные средства, реализующие один или несколько криптографических алгоритмов (шифрование, выработка и проверка электронной цифровой подписи, хэширование, имитозащита) и криптографические протоколы, а также функции управления криптографическими ключами и функциональные возможности безопасности;

У этого определения есть несколько проблем:
- не сделан акцент на "внешнее использование". И процессор Intel, и Git можно классифицировать как СКЗИ;
- жесткое перечисление типов криптографических алгоритмов. При буквальном чтении можно понять, что за бортом остается и шифрование с открытым ключом, и разнообразные протоколы, и многое другое;
- "функциональные возможности безопасности" -- неудачно. Слово "возможности" вообще нельзя использовать, нужно менять на что-то вроде "средства"  или "механизмы". Но даже после замены фраза "функциональные средства безопасности" труднопонимаема без привязки к контексту Общих Критериев. Напомню, что у нас такой привязки нет и не будет.

**Comment by NikGomel** [comment]
> не сделан акцент на "внешнее использование". И процессор Intel, и Git можно классифицировать как СКЗИ; 
жесткое перечисление типов криптографических алгоритмов. При буквальном чтении можно понять, что за бортом остается и шифрование с открытым ключом, и разнообразные протоколы, и многое другое;

в определении можно указать фразу "интерфейс взаимодействия":
средства криптографической защиты информации – программные, программно- аппаратные средства, реализующие один или несколько криптографических алгоритмов и интерфейсов взаимодействия, а также функции управления криптографическими ключами....

**Comment by saverchenko** [comment]
А что если в определение СКЗИ добавить "... реализующие один или несколько **белорусских** криптографических алгоритмов, которые определены в стандартах серии СТБ 31.101.*,  ..."? Таким образом процессоры Intel, Git и т.п. не попадут под определение СКЗИ.

**Comment by agievich** [comment]
Нет, так нельзя. Мы же говорим о каких-то особенных (белорусских) СКЗИ.
