### ISSUE TITLE
Программное vs аппаратное vs аппаратно-программное

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#4]
Чем отличаются друг от друга программное, аппаратное и аппаратно-программное СКЗИ?

СКЗИ -- это набор аппаратных и программных компонентов (см. #3 ). При этом (действующее определение):
> Программное СКЗИ: СКЗИ, выполненное целиком программно, без аппаратных     компонентов.

Можно механически продолжить:

> Аппаратное СКЗИ: СКЗИ, выполненное целиком аппаратно, без программных     компонентов.

> Аппаратно-программное СКЗИ: СКЗИ, включающее и аппаратные, и программные компоненты.

При этом под аппаратными СКЗИ будут пониматься электромеханические устройства (например, машины Энигма или Фиалка), которые не применяются в настоящее время.

**Предлагается** отказаться от чисто аппаратных (без программного обеспечения) СКЗИ и 
поступить так: 

1. Термин "аппаратно-программное СКЗИ" не используется.
2. Под "СКЗИ" понимается "аппаратное СКЗИ": и аппаратура, и программы. Можно говорить и "СКЗИ", и "аппаратное СКЗИ". Разницы нет.
3. Определение "программное СКЗИ" сохраняется.

**Comment by zm1ca** [comment]
Отказ от чисто аппаратных СКЗИ разумен и уже предусмотрен в новой редакции Приказа ОАЦ №62. Замена понятия "программно-аппаратное СКЗИ" на "аппаратное СКЗИ" имеет следующие проблемы:

**Comment by NikGomel** [comment]
Понятие программно-аппаратного СКЗИ должно быть отдельно. В нашем законодательстве прописано, что для защиты служебной информации ограниченного распространения используются только программно-аппаратные СКЗИ.

**Comment by agievich** [comment]
**Предлагаю** приравнять: аппаратно-программное = программно-аппаратное = аппаратное.

**Comment by zm1ca** [comment]
Локально (в рамках стандарта), это будет удобнее. Однако глобально это может вызвать некоторый диссонанс в терминологии. Нужно определиться, удобство какого порядка нам приоритетнее. Лично я считаю, что удобство чтения данного стандарта важнее удобства дальнейшего восприятия законов, однако нужно очень тщательно продумать, как дать новому читателю понять концепцию "программного+аппаратного" (п.2 https://github.com/bcrypto/skzi/issues/4#issuecomment-580154250), а прочим читателям явно дать понять, что произошла умышленная замена термина.

**Comment by agievich** [comment]
Не совсем понял про умышленную замену термина. Речь идет о том, что при вводе  определений термины "аппаратно-программное", "программно-аппаратное" и " аппаратное" уравниваются. 

Например,

**аппаратное (аппаратно-программное, программно-аппаратное) СКЗИ**: ...

Или

**аппаратно-программное СКЗИ**: см. аппаратное СКЗИ;
**программно-аппаратное СКЗИ**: см. аппаратное СКЗИ;

**Comment by zm1ca** [comment]
Да, на мой взгляд это было бы достаточно понятно и удобно.

**Comment by andrewkostevich** [comment]
**Программное СКЗИ.**  СКЗИ поставляемое в виде пакета программного обеспечания, которое пользователь сам устанавливает/удаляет/обновляет на удобные для него вычислительные системы.
 
Пример - браузеры Google-Crome или Mozillа которые реализуют симметричную криптографию, хэширование, проверку подписи (для реализации протокола TLS) и обслуживания цепочек сертификатов. 

**Аппаратные СКЗИ.** СКЗИ поставляемые в виде аппаратного изделия, на котором пользователь не может воздействовать на размещенные в нем СКЗИ. Заменить/обновить СКЗИ может только производитель. 

Примеры:  ID-карта, СИМ-карта, чиповая-банковская платежная карта, банковский POS-терминал.

**Программно-аппаратные СКЗИ и аппаратно-программные СКЗИ**.  Комплекс из двух видов СКЗИ - аппаратного и программного. Комплекс относится к аппаратно-программному, если он обеспечивает обработку долговременных личных (секретных) ключей аппаратным СКЗИ, в иных случаях это программно-аппаратный комплекс.

Примеры: 1. cмарт-карта с модулем PKCS#11, подпись реализована как апаратное СКЗИ, 
хэширование и проверка подписи реализованы программно в модуле PKCS#11. 
Браузер с плагином для чиповой смарт-карты.

Из этого вытекает: аппаратные и аппаратно-програмные - личные ключи "не покидают"
Программные и программно-аппаратные-"покидают"

**Comment by agievich** [comment]
Фактически предлагается ввести те же 4 уровня. Просто назвать их по-другому и по-другому расставить характеризационные признаки (триггеры).

Сразу скажу, что если потребуется ввести термины "аппаратное СКЗИ", "аппаратно-программное", "программно-аппаратное" в предлагаемом ключе, то будут проблемы: определение не может содержать требований.

Не очень разобрался с триггерами. "Пользователь не может воздействовать на СКЗИ, размещенные в аппаратном изделии". Что это за изделие? СКЗИ? Но тогда как пользователь не может воздействовать на СКЗИ, если он работает с СКЗИ. И что значит "воздействовать"? Штатно или нештатно?

Я подозреваю, что имеется здравая концепция. Но она должна быть представлена яснее.

**Comment by agievich** [comment]
Термины "аппаратное СКЗИ", "аппаратно-программное СКЗИ" и "программно-аппаратное СКЗИ" сделаны эквивалентными в v3.1.
