### ISSUE TITLE
Untrust/Semitrust/Trust

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#5]
Предлагается обсудить следующие тезисы. В них вводятся (напоминаются) некоторые важные 
концепции и определения, задается общая схема требований безопасности.

1. _Криптографическая граница_ СКЗИ -- это непрерывный физический периметр, 
за пределами которого -- потенциально агрессивная среда, зона Untrust. 
Разработчик СКЗИ не должен делать предположений о том, что находится за 
границей. Но он может делать предположения о том, что находится в пределах 
границы.

2. Область в пределах криптографической границы -- это _системная среда_ СКЗИ. 
В среде выделяются системные компоненты -- процессор, устройства хранения, 
устройства сопряжения, операционная система и др. Системная среда может быть 
фиксированной (жесткий список компонентов) или модифицируемой (примерный список 
компонентов, определенная свобода при выборе того или иного компонента).

3. Список компонентов СКЗИ объявляется разработчиком. Компоненты СКЗИ 
встраиваются в системную среду (примеры -- установка программ ПСКЗИ, установка 
криптографической платы в слот расширения) или образуют эту среду (пример -- 
самостоятельный аппаратный токен). Даже если компонент входит в 
состав СКЗИ, он может классифицироваться как системный. Примеры -- 
микроконтроллер криптографической платы, операционная система 
аппаратного токена.

4. Принципы отнесения компонентов к системным: 
- системные компоненты являются универсальными, они не ориентированы на 
выполнение исключительно криптографических сервисов; 
- системные компоненты являются массовыми, они разрабатываются без связи с СКЗИ; 
- системные компоненты являются внешними по отношению к СКЗИ, при разработке 
СКЗИ они только интегрируются и возможно конфигурируются.

5. Разработчик СКЗИ определяет _критические системные компоненты_ (КСК). Это 
подмножество системных компонентов. КСК и только они влияют на безопасность 
СКЗИ или поддерживают безопасность. 

6. Даже если критический системный компонент входит в состав СКЗИ, контроль 
над ним остается достаточно условным. КСК и системная среда в целом являются 
для СКЗИ зоной Semitrust: "доверяй, но проверяй".

7. Факторы Semitrust:
- непрозначность, не до конца понятная логика работы (проприетарных компонентов);
- сложность и как следствие высокая вероятность ошибок (в операционных системах);
- модифицируемость (установка новых программ с непредсказуемым поведением);
- доступ нескольких операторов (риск чтения активов друг друга);
- сбои (в аппаратных компонентах).

8. Зоной Trust остаются собственные компоненты СКЗИ, не являющиеся системными. 
Как правило, это исключительно программные компоненты: прошивки, 
конфигурационные файлы, криптоконтейнеры операторов и пр.

9. В соответствии с делением Utrust/Semitrust/Trust определены следующие направления защиты:
- защита криптографической границы, отделяющей от зоны Untrust;
- повышение доверия в зоне Semitrust;
- надежность и качество в зоне Trust.

10. Защита границы (периметра) -- это:
- физическая защита от проникновения: корпус, датчики вскрытия;
- логическая защита от проникновения: аутентификация;
- защита от побочных каналов: по времени выполнения, ПЭМИН.

11. Повышение доверия в зоне Semitrust -- это:
- контроль состава КСК;
- контроль работоспособности КСК (тестирование при запуске, по запросу, периодическое);
- контроль интерфейсов взаимодействия (неверный коммуникационный пакет не приведет к сбою);
- настройка КСК (напр., настройки безопасности операционной системы);
- отслеживание статуса безопасности КСК (учет информации об обнаруженных уязвимостях);
- выборочный анализ исходных текстов;
- выборочное тестирование.

12. Надежность и качество в зоне Trust -- это:
- надежные криптографические алгоритмы;
- надежные механизмы безопасности;
- надежное криптографическое проектирование (криптоинжиниринг);
- полномасштабный анализ исходных текстов;
- полномасштабное тестирование;
- надежный жизненный цикл;
- подробные руководства.

**Comment by zm1ca** [comment]
> надежные криптографические алгоритмы;
надежные механизмы безопасности;
надежное криптографическое проектирование (криптоинжиниринг);

подразумевает возможность использования ненадёжных алгоритмов и прочего в других классах

> защита криптографической границы, отделяющей от зоны Untrust;
повышение доверия в зоне Semitrust;
надежность и качество в зоне Trust.

На данный момент деление довольно абстрактное, не дающее полной ясности для разработчиков, и не позволяющее внятно регулировать/разделять.

> Список компонентов СКЗИ объявляется разработчиком.

Потребуется строгое объяснение того, что именно разработчик должен выделить как компонент. Чем хуже разработчик поймёт - тем более мучительно будет с этим разбираться. Думаю, стоит насытить данный раздел примерами.

В целом: концепция удобная и полезная, но не должна стать слишком тяжеловесной в итоге. Хотелось бы, чтобы с основами ознакомились наиболее широкие круги разработчиков.

**Comment by agievich** [comment]
> Думаю, стоит насытить данный раздел примерами.

Текст выше -- это не раздел будущего стандарта. Это проработка концепции с неявным предложением участвовать в обсуждении, в том числе, в формировании терминологии.

**Comment by komisarenkov** [comment]
1.	Криптографическая граница СКЗИ -- это непрерывный физический периметр,
за пределами которого -- потенциально агрессивная среда, зона Untrust.
//удалить: Разработчик СКЗИ не должен делать предположений о том, что находится за
границей. Но он может делать предположения о том, что находится в пределах
границы.
2.	Область в пределах криптографической границы -- это системная среда в которой исполняются криптографические алгоритмы.
//удалить: В среде выделяются системные компоненты -- процессор, устройства хранения,
устройства сопряжения, операционная система и др. Системная среда может быть
фиксированной (жесткий список компонентов) или модифицируемой (примерный список
компонентов, определенная свобода при выборе того или иного компонента).
3.	Список компонентов СКЗИ объявляется разработчиком. Компоненты СКЗИ
встраиваются в системную среду //удалить: (примеры -- установка программ ПСКЗИ, установка
криптографической платы в слот расширения) или образуют эту среду (пример --
самостоятельный аппаратный токен). Даже если компонент входит в
состав СКЗИ, он может классифицироваться как системный. Примеры --
микроконтроллер криптографической платы, операционная система
аппаратного токена.
4.	Принципы отнесения компонентов к системным://не ясно зачем это
•	системные компоненты являются универсальными, они не ориентированы на
выполнение исключительно криптографических сервисов;
•	системные компоненты являются массовыми, они разрабатываются без связи с СКЗИ;
•	системные компоненты являются внешними по отношению к СКЗИ, при разработке
СКЗИ они только интегрируются и возможно конфигурируются.
5.	Разработчик СКЗИ определяет критические системные компоненты (КСК). Это
подмножество системных компонентов. КСК и только они влияют на безопасность
СКЗИ или поддерживают безопасность.//все компоненты влияют на безопасность
6.	Даже если критический системный компонент входит в состав СКЗИ, контроль
над ним остается достаточно условным. КСК и системная среда в целом являются
для СКЗИ зоной Semitrust: "доверяй, но проверяй".//мутно как-то
7.	Факторы Semitrust:
•	непрозначность, не до конца понятная логика работы (проприетарных компонентов);//зачем такое использовать
•	сложность и как следствие высокая вероятность ошибок (в операционных системах);//как это оценить?
•	модифицируемость (установка новых программ с непредсказуемым поведением);
•	доступ нескольких операторов (риск чтения активов друг друга);//это необходимо раскрыть
•	сбои (в аппаратных компонентах).
8.	Зоной Trust остаются собственные компоненты СКЗИ, не являющиеся системными.
Как правило, это исключительно программные компоненты: прошивки,
конфигурационные файлы, криптоконтейнеры операторов и пр.//тогда получается: скзи состоит из системной среды и непосредственно реализаций криптоалгоритмов и связанных данных. Скзи эксплуатируется в среде функционирования
9.	В соответствии с делением Utrust/Semitrust/Trust определены следующие направления защиты://не удачно
•	защита криптографической границы, отделяющей от зоны Untrust;//не удачно. Защищать нужно активы скзи, а не границу
•	повышение доверия в зоне Semitrust;
•	надежность и качество в зоне Trust.
10.	Защита границы (периметра) -- это://все это должно быть в контексте защиты активов скзи
•	физическая защита от проникновения: корпус, датчики вскрытия;
•	логическая защита от проникновения: аутентификация;
•	защита от побочных каналов: по времени выполнения, ПЭМИН.
11.	Повышение доверия в зоне Semitrust -- это:
•	контроль состава КСК;//что это значит практически?
•	контроль работоспособности КСК (тестирование при запуске, по запросу, периодическое);
•	контроль интерфейсов взаимодействия (неверный коммуникационный пакет не приведет к сбою);
•	настройка КСК (напр., настройки безопасности операционной системы);//не удачно. Настройка всегда какая-то есть
•	отслеживание статуса безопасности КСК (учет информации об обнаруженных уязвимостях);//допускается работа с обнаруженными уязвимостями?
•	выборочный анализ исходных текстов;
•	выборочное тестирование.
12.	Надежность и качество в зоне Trust -- это:
•	надежные криптографические алгоритмы;
•	надежные механизмы безопасности;//защищенность активов
•	надежное криптографическое проектирование (криптоинжиниринг);//это не ясно что
•	полномасштабный анализ исходных текстов;
•	полномасштабное тестирование;
•	надежный жизненный цикл;
•	подробные руководства.

**Comment by agievich** [comment]
Концепция реализована в v3.1.
