### ISSUE TITLE
Provide versioned readable online HTML version with section anchors

### ISSUE THREAD

**Issue by abitrolly** [bcrypto/skzi#7]
To move the process forward, there should be an efficient mechanism to permalink to all parts of all revisions of specification online.

**Comment by zm1ca** [comment]
Поддерживаю, стоит снижать порог вхождения в существующую систему стандартизации. Удобство обсуждений приведёт к повышению их продуктивности.

**Comment by agievich** [comment]
Наш движок -- система LaTeX с выводом релизных pdf-файлов. Примерно так ведется разработка ISO стандартов, стандартов NIST.  Для файлов с преимущественно текстовым содержимым мы иногда используем markdown (см. https://github.com/bcrypto/stb). Но здесь не тот случай: будут формулы, будет много внутренних связей, нужна сильная автоматизация.

Присылайте замечания и предложения по pdf-файлам. Зачем HTML. 

> Поддерживаю, стоит снижать порог вхождения в существующую систему стандартизации. Удобство обсуждений приведёт к повышению их продуктивности.

Не понял, что поддерживается. О каком "пороге вхождения" идет речь? В существующей системе стандартизации разработка стандартов ведется в MS Word.

**Comment by abitrolly** [comment]
Жесть. Работа с LaTeX ведётся в MS Word. Если стандартизаторы неспособны использовать в работе открытые технологии, не понимают фразу "порог вхождения", то возникает вопрос целесообразности тратить своё время на людей, на способных применять ничего новое, ведь способности к обучению и адаптации у них тоже низки.

Я всячески приветствую вытянуть обсуждения отечественных криптотехнологий в паблик. После 20 лет незнамо чего, наконец-то увидеть хоть что-то. Надеюсь, что вы достаточно толстокожи, чтобы воспринимать критику должным образом.

**Comment by zm1ca** [comment]
> на способных применять ничего новое, ведь способности к обучению и адаптации у них тоже низки
Открытое обсуждение - это хорошо, но оно не должно быть грубым.

> О каком "пороге вхождения" идет речь?
Порог вхождения в моём понимании высокий в том смысле, что не купив доступ к стандартам, человек не знает о чём ведётся речь в разрабатываемых. В то же время, покупать стандарты просто для обсуждения - странно, и этим никто не занимается. Переходить по ссылкам на пункты других стандартов было бы удобно (думаю, о механизме с такой функцией и велась речь). Правда, вряд ли это вопрос к Вам и в этом репозитории.

**Comment by agievich** [comment]
Странные и неуместные высказывания @abitrolly. Открытое обсуждение криптографических стандартов ведется на протяжении (как минимум) последних 10 лет.
