### ISSUE TITLE
Перечень пакетов

### ISSUE THREAD

**Issue by agievich** [bcrypto/skzi#9]
В текущей редакции СТБ 34.101.27 определены следующие пакеты требований к СКЗИ:
- КП (криптографическая поддержка);
- РС (реализация сервисов);
- УД (управление доступом);
- ЗО (защита объектов);
- СТ (самотестирование);
- СЧ (случайные числа);

и к системной среде (так мы сейчас говорим; могут реализовываться самим СКЗИ):
- ИА (идентификация и аутентификация);
- НС (настройка среды).

Есть еще пакеты гарантийных требований (требования качества):
- ПР (проектирование и разработка);
- ЖЦ (жизненный цикл);
- РД (руководства);
- ПИ (программа испытаний).

Пакеты будут расширяться (с учетом расширения числа уровней), но текущие требования пакетов будем стараться сохранять. Редакционных поправок намечается много, но технические поправки -- только в самых необходимых случаях (для сохранения преемственности и обеспечения плавного перехода). 

Намечаются новые пакеты. Некоторые из них будут опциональными, некоторые обязательными на определенных уровнях.

Вот пилотный перечень дополнительных пакетов:
- ФБ (физическая безопасность) [СКЗИ];
- ЗВ (защита от воздействий) [СКЗИ; напряжение, температура];
- ЗУ (защита от утечек) [СКЗИ; ПЭМИН];
- ОИ (опасные интерфейсы) [среда];
- АУ (аудит) [среда];
- ОП (обновление программ) [СКЗИ; опциональный];
- ВЭ (вывод из эксплуатации -- очистка критических объектов) [СКЗИ; опциональный];
- ДК (доверенный канал) [СКЗИ; опциональный; для связи с удаленным СКЗИ].

Планируется маркировка: **2[ОП,ДК]** -- СКЗИ 2-го уровня с дополнительными пакетами ОП, ДК.

**Comment by olegotory** [comment]
Дополнительные пакеты для обсуждения:
- СК (смена ключей); содержит требования по контролю срока действия долговременных ключей, блокировке (уничтожению?) ключей с истекшим сроком действия, установке новых ключей и др.;
- ИВ (источник времени); содержит требования к точности источника времени, синхронизации времени и др. пакет нужен, например, для службы штампов времени, удостоверяющих центров, ocsp-серверов.

**Comment by Siarhei-St** [comment]
Нужный и интересный пакет ОП. Сразу же напрашивается вопрос - какие требования он должен содержать, чтобы упростить (ускорить) процедуры сертификации СКЗИ, и возможно ли такое упрощение в настоящее время "в принципе" при наличии какого-либо пакета ОП?  Без влияния пакета ОП на процедуру сертификации, необходимость его, на мой взгляд,  под вопросом.

**Comment by agievich** [comment]
Предложенный перечень пакетов реализован в v3.1.
